version: '3'
services:
  master:
    ports: 
      - "127.0.0.1:7077:7077"
      - "127.0.0.1:8088:8088"
      - "127.0.0.1:4040:4040"
      - "127.0.0.1:18080:18080"
    networks:
      spark-network:
        ipv4_address: 172.18.0.20
    hostname: spark-master
    volumes:
       - ./shared-master:/home/sparker/shared
    image: "spark_compose_master:latest"
  slave:
    ports:
      - "7177"
      - "8042"
    environment:
       - "script=run_slave.sh"
    networks:
      - spark-network
    volumes:
       - ./shared-slave:/home/sparker/shared
    extra_hosts:
      - "spark-master:172.18.0.20"
    depends_on:
    -  master
    image: "spark_compose_slave:latest"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - ELASTIC_PASSWORD=foobar
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml  
    networks:
      - spark-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    container_name: kibana
    # environment:
     # ELASTICSEARCH_URL: http://elasticsearch:9200
    #  ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      # - XPACK_SECURITY_ENABLED=true
      # - ELASTICSEARCH_USERNAME=elastic
      # - ELASTICSEARCH_PASSWORD=foobar
    ports:
      - "5601:5601"
    networks:
      - spark-network
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml      
    depends_on:
      - elasticsearch
 
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16
